"""Generate column metadata HTML reference table."""

from __future__ import annotations

import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from dashboard.column_meta import COLUMN_META, FILTER_TYPE_OVERRIDE, get_filter_type
from dashboard.data_loader import EPC_TABLE_COLUMNS


# Friendly filter type names
_FILTER_LABELS = {
    "agSetColumnFilter": "Checkbox set",
    "agNumberColumnFilter": "Number range",
    "agTextColumnFilter": "Text search",
    "agDateColumnFilter": "Date picker",
}


def generate_html() -> str:
    rows = []
    for col in EPC_TABLE_COLUMNS:
        display, tooltip = COLUMN_META.get(col, (col.replace("_", " ").title(), ""))
        ftype = get_filter_type(col)
        flabel = _FILTER_LABELS.get(ftype, ftype)
        override = "override" if col in FILTER_TYPE_OVERRIDE else "auto"
        rows.append(
            f"<tr><td><code>{col}</code></td><td>{display}</td>"
            f"<td>{tooltip}</td><td>{flabel} <small>({override})</small></td></tr>"
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>EPC Explorer — Column Reference</title>
<style>
body {{ font-family: 'Open Sans', Arial, sans-serif; margin: 2rem; background: #F0F0F5; color: #282850; }}
h1 {{ color: #282850; font-family: 'Lora', serif; }}
table {{ border-collapse: collapse; width: 100%; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.12); }}
th {{ background: #282850; color: #CBAC88; padding: 10px 12px; text-align: left; }}
td {{ padding: 8px 12px; border-bottom: 1px solid #E0E0E5; }}
tr:hover {{ background: #F5F5FA; }}
code {{ background: #E8E8ED; padding: 2px 6px; border-radius: 4px; font-size: 0.85rem; }}
.footer {{ margin-top: 2rem; font-size: 0.85rem; color: #7F7F85; }}
</style>
</head>
<body>
<h1>EPC Explorer — Column Reference</h1>
<p>Mapping between database column names, dashboard display names, and tooltip descriptions.
Edit <code>src/dashboard/column_meta.py</code> to update. Regenerate with <code>py src/dashboard/generate_column_ref.py</code>.</p>
<table>
<thead><tr><th>Database Column</th><th>Dashboard Name</th><th>Tooltip / Description</th><th>Filter Type</th></tr></thead>
<tbody>
{"".join(rows)}
</tbody>
</table>
<p class="footer">Generated by <code>src/dashboard/generate_column_ref.py</code>. {len(rows)} columns.</p>
</body>
</html>"""


if __name__ == "__main__":
    out = _PROJECT_ROOT / "output" / "column_reference.html"
    out.write_text(generate_html(), encoding="utf-8")
    print(f"Written: {out} ({out.stat().st_size:,} bytes)")
